language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz python-tk
install:
  - travis_retry pip install Sphinx
  - travis_retry pip install pep8
  - travis_retry pip install coverage
  - travis_retry pip install coveralls
script:
  - python -Wall setup.py try
  - python setup.py install
  - python -Wall setup.py test
  - coverage run test/runtest.py
  - python run.py --doctest
  - python run.py --html
after_script:
  - pep8 --exclude=asizeof.py,metadata.py,bottle*.py --max-line-length=80 pympler
after_success:
  - coveralls
